import { PrismaClient, RoleType } from "@prisma/client";

export const users = [
  {
    username: "johndoe",
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    password: "pass",
    age: 25,
    role: RoleType.waiter,
    phoneNumber: "1234567890",
    contract: "Contract A",
  },
  {
    username: "janedoe",
    firstName: "Jane",
    lastName: "Doe",
    email: "janedoe@example.com",
    password: "pass",
    age: 30,
    role: RoleType.cashier,
    phoneNumber: "0987654321",
    contract: "Contract B",
  },
  {
    username: "alice",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice@example.com",
    password: "pass",
    age: 28,
    role: RoleType.chief,
    phoneNumber: "1122334455",
    contract: "Contract C",
  },
  {
    username: "bob",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob@example.com",
    password: "pass",
    age: 35,
    role: RoleType.finance,
    phoneNumber: "5566778899",
    contract: "Contract D",
  },
  {
    username: "carol",
    firstName: "Carol",
    lastName: "Williams",
    email: "carol@example.com",
    password: "pass",
    age: 40,
    role: RoleType.stocker,
    phoneNumber: "6677889900",
    contract: "Contract E",
  },
];
