name: Production Ci/CD

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout
      - name: Install Dependencies
        run: npm install
      - name: Run build
        run: npm run build
  deploy:
    name: Deploy To Production
    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Render
        uses: johnbeynon/render-deploy-action
        with:
          service-id: ${{secrets.PRO_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
